<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateEspeciess extends Migration{
	public function up(){ 
 		Schema::create('especiess', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->string('nombre');
			$table->string('associated_habitat');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}