<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Actividad extends Model
{
    protected $fillable = [
        'nombre',
        'cronograma',
        'associated_animals',
    ];

    public function animals()
    {
        return $this->belongsToMany('App\Models\Animal');
    }
}
