<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'especies',
        'habitat',
        'cuidador_id',
    ];

    public function especies()
    {
        return $this->hasOne(\App\Models\Especies);
    }

    public function recintoss()
    {
        return $this->hasMany('App\Models\Recintos');
    }

    public function cuidador()
    {
        return $this->hasOne(\App\Models\Cuidador);
    }

    public function especies()
    {
        return $this->belongsTo('App\Models\Especies');
    }

    public function recintoss()
    {
        return $this->belongsToMany('App\Models\Recintos');
    }

    public function cuidador()
    {
        return $this->belongsTo('App\Models\Cuidador');
    }

    public function actividads()
    {
        return $this->belongsToMany('App\Models\Actividad');
    }
}
