<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Cuidador extends Model
{
    protected $fillable = [
        'nombre',
        'especialidad',
    ];

    public function animal()
    {
        return $this->belongsTo('App\Models\Animal');
    }

    public function animals()
    {
        return $this->hasMany('App\Models\Animal');
    }
}
